using System.Collections;
using System.Collections.Generic;
using UnityEngine;

public enum EnumEvents
{
    KILL_FLOOR_HIT,
    HOT_ZONE_EXIT,
    FLIP_CULTIST,
    PLAYER_DEAD,
    CULTIST_DEAD,
    ABOMINATION_DEAD,
    LOAD_ABOMINATION,
    SAVE_ABOMINATION,

    TUTORIAL_TO_CASTLE,
    CASTLE_TO_TUTORIAL,
    CASTLE_TO_BOSS,

    LOAD_PLAYER,
    SKULLY_HIT_UPPER_LEFT,
    SKULLY_HIT_UPPER_RIGHT,
    SKULLY_HIT_UPPER_CENTER,
    SKULLY_HIT_SPAWN_POINT

}
